apiVersion: v1
kind: ServiceAccount
metadata:
  name: azure-policy-delete-admin
  namespace: kube-system
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "20"
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: azure-policy-delete-agent
  namespace: kube-system
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "20"
rules:
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["delete"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: azure-policy-delete-agent
  namespace: kube-system
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "20"
subjects:
- kind: ServiceAccount
  name: azure-policy-delete-admin
  namespace: kube-system
roleRef:
  kind: Role
  name: azure-policy-delete-agent
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: batch/v1
kind: Job
metadata:
  name: azure-policy-pre-delete
  namespace: kube-system
  annotations:
    "helm.sh/hook": pre-delete
    "helm.sh/hook-delete-policy": "hook-succeeded"
spec:
  template:
    spec:
      serviceAccountName: azure-policy-delete-admin
      automountServiceAccountToken: true 
      restartPolicy: Never
      terminationGracePeriodSeconds: 0
      containers:
        - name: azure-policy-pre-delete
          image: {{ .Values.alpinecurl.image.name }}:{{ .Values.alpinecurl.image.tag }}
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          imagePullPolicy: IfNotPresent
          command: 
            - "/bin/sh"
            - "-ec"
            - |
              set -o pipefail
              TOKEN=$(cat /var/run/secrets/kubernetes.io/serviceaccount/token)
              curl -s -X DELETE -k https://kubernetes.default.svc/apis/apps/v1/namespaces/${NAMESPACE}/deployments/azure-policy \
                -H "Authorization: Bearer ${TOKEN}" \
                -H "Content-Type: application/json" \
                -d '{"kind":"DeleteOptions","apiVersion":"v1","propagationPolicy":"Foreground"}'
              sleep 30
