apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sTestContainerLimits
metadata:
  name: container-limits
spec:
  match:
    excludedNamespaces: {{ .Values.excludedNamespaces }}
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
  parameters:
    cpuLimit : "{{ .Values.cpuLimit }}"
    memoryLimit: "{{ .Values.memoryLimit }}"