apiVersion: templates.gatekeeper.sh/v1beta1
kind: ConstraintTemplate
metadata:
  name: loadbalancernopublicips
spec:
  crd:
    spec:
      names:
        kind: LoadbalancerNoPublicips
  targets:
    - target: admission.k8s.gatekeeper.sh
      rego: |
        package loadbalancernopublicips

        violation[{"msg": msg}] {
          not loadbalancer_no_pip(input.review.object)
          msg := sprintf("Loadbalancers should not have public ips. azure-load-balancer-internal annotation is required for %v", [input.review.object.metadata.name])
        }
    
        loadbalancer_no_pip(service) = true {
          service.spec.type == "LoadBalancer"
          service.metadata.annotations["service.beta.kubernetes.io/azure-load-balancer-internal"] == "true"
        }

        loadbalancer_no_pip(service) = true {
          service.spec.type != "LoadBalancer"
        }