---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: azure-policy-addon-arc-clusters
  namespace: kube-system
  annotations:
    flux.weave.works/automated: "false"
    flux.weave.works/tag.chart-image: semver:~4.0
spec:
  releaseName: azure-policy-addon-arc-clusters
  chart:
    repository: https://raw.githubusercontent.com/RamyasreeChakka/RegoPolicy/master/Kubernetes/helmcharts/
    name: azure-policy-addon-arc-clusters
    version: 0.1.0
  values:
    azurepolicy:
      env:
        resourceid: /subscriptions/44d01367-c909-4ddc-94ef-9c4a4b34ed23/resourceGroups/ramya-perf30-akse-test2-arc/providers/Microsoft.Kubernetes/connectedClusters/ramya-perf30-akse-test2-arc-cluster
        clientid: <client id>
        clientsecret: <secret>
        tenantid: <tenant id>
