name: Helm chart update check for AKS Engine
on:
  push:
    branches:
      - master
    paths:
      - 'Kubernetes/helmcharts/azure-policy-addon-aks-engine/**'
  pull_request:
    branches:
      - master
    paths:
      - 'Kubernetes/helmcharts/azure-policy-addon-aks-engine/**'
jobs:
  test:
    name: Test Helm chart update
    runs-on: ubuntu-latest

    env:
      AZURE_CREDENTIALS: ${{ secrets.TEST_AZURE_CREDENTIALS }}
      SubscriptionId: ""
      ResourceGroupName: ""
      ClusterName: ""
      ClusterResourceId: ""
      ClusterType: ""
      ClientId: ""      
      ClientSecret: ""

    steps:

    - name: Checkout code
      uses: actions/checkout@v2

    - shell: bash
      run: |
        currentDateTime=`date +"%Y%m%d%H%M%S"`
        echo "time is ${currentDateTime}"
        echo set-env ClusterType="aks-engine-test"
        echo ::set-env SubscriptionId=$(echo "$AZURE_CREDENTIALS" | jq .'subscriptionId' -r)
        export ClientId=$(echo "$AZURE_CREDENTIALS" | jq .'clientId' -r)
        export ClientSecret=$(echo "$AZURE_CREDENTIALS" | jq .'clientSecret' -r)
        export ResourceGroupName=$(echo "testRG$currentDateTime")
        export clusterResourceId=$(echo "/subscriptions/$SubscriptionId/resourceGroups/$ResourceGroupName")
        echo "Next Sub ID is $SubscriptionId"
        echo "Next ClusterType is $ClusterTYpe"        

    - shell: bash
      run: |
        echo "Test env variables"
        echo "Next Sub ID is $SubscriptionId"
        echo "Next ClusterType is $ClusterTYpe"
 
    - name: Logon to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.TEST_AZURE_CREDENTIALS }}

    - name: Create AKS Engine cluster
      uses: azure/CLI@v1
      with: 
        inlineScript: |
          chmod +x $GITHUB_WORKSPACE/scripts/testScript.sh
          $GITHUB_WORKSPACE/scripts/testScript.sh $ClusterType $SubscriptionId $ResourceGroupName $ClientId $ClientSecret
      
