name: Helm chart update check for AKS Engine
on:
  push:
    branches:
      - master
    paths:
      - 'Kubernetes/helmcharts/azure-policy-addon-aks-engine/**'
  pull_request:
    branches:
      - master
    paths:
      - 'Kubernetes/helmcharts/azure-policy-addon-aks-engine/**'
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Checkout code
      uses: actions/checkout@v2
 
    - name: Logon to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Create AKS Engine cluster
      uses: azure/CLI@v1
      with: 
        inlineScript: |
          chmod +x $GITHUB_WORKSPACE/scripts/testScript.sh
          $GITHUB_WORKSPACE/scripts/testScript.sh
